from typing import Protocol


class SandboxSession(Protocol):
    def run(self, command: str, cwd: str = ".", timeout: int = 60) -> str: ...
    def read_file(self, path: str) -> str: ...
    def write_file(self, path: str, content: str) -> str: ...
    def stop(self) -> str: ...
    def delete(self) -> str: ...
    def stop_and_delete(self) -> str: ...


class SandboxProvider(Protocol):
    def create(self) -> SandboxSession: ...
